/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarUpload: typeof import('./src/components/AvatarUpload.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FolderSelect: typeof import('./src/components/FolderSelect.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    Preview: typeof import('./src/components/preview/Preview.vue')['default']
    PreviewDoc: typeof import('./src/components/preview/PreviewDoc.vue')['default']
    PreviewDownload: typeof import('./src/components/preview/PreviewDownload.vue')['default']
    PreviewExcel: typeof import('./src/components/preview/PreviewExcel.vue')['default']
    PreviewImage: typeof import('./src/components/preview/PreviewImage.vue')['default']
    PreviewMusic: typeof import('./src/components/preview/PreviewMusic.vue')['default']
    PreviewPdf: typeof import('./src/components/preview/PreviewPdf.vue')['default']
    PreviewTxt: typeof import('./src/components/preview/PreviewTxt.vue')['default']
    PreviewVideo: typeof import('./src/components/preview/PreviewVideo.vue')['default']
    PreviewVideo_hls: typeof import('./src/components/preview/PreviewVideo_hls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    Window: typeof import('./src/components/Window.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
